baseURL = "https://www.angularcorp.com/"
languageCode = "en-us"
title = "Application Deveopment"

staticDir = ["static", "themes/Niello/static"]

[params]
keywords = ""   //SEO keywords
description = ""    //Site description
copyright = "&#xA9; 2019 - 2022 by guangmean. All Rights Reserved."
google_ad_client = "ca-pub-******"  //Optional, replace ca-pub-****** with your content
ga = "UA-******" //Optional, replace UA-****** with your content
sharethis = ""  //Optional, Add hou ShareThis appid here

[menu]
    [[menu.niello]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.niello]]
    name = "About"
    url = "/about/"
    weight = 2